import { AfterViewInit, ElementRef, EventEmitter, NgZone, OnChanges, OnDestroy, Renderer2, SimpleChange } from '@angular/core';
import Plyr from 'plyr';
import { PlyrDriver } from '../plyr-driver/plyr-driver';
export declare class PlyrComponent implements AfterViewInit, OnChanges, OnDestroy {
    private elementRef;
    private ngZone;
    private renderer;
    private playerChange;
    readonly player: Plyr;
    private events;
    plyrDriver: PlyrDriver;
    plyrType: Plyr.MediaType;
    plyrTitle: string;
    plyrPoster: string;
    plyrSources: Plyr.Source[];
    plyrTracks: Plyr.Track[];
    plyrOptions: Plyr.Options;
    plyrCrossOrigin: boolean;
    plyrPlaysInline: boolean;
    private vr;
    plyrInit: EventEmitter<any>;
    plyrProgress: EventEmitter<{}>;
    plyrPlaying: EventEmitter<{}>;
    plyrPlay: EventEmitter<{}>;
    plyrPause: EventEmitter<{}>;
    plyrTimeUpdate: EventEmitter<{}>;
    plyrVolumeChange: EventEmitter<{}>;
    plyrSeeking: EventEmitter<{}>;
    plyrSeeked: EventEmitter<{}>;
    plyrRateChange: EventEmitter<{}>;
    plyrEnded: EventEmitter<{}>;
    plyrEnterFullScreen: EventEmitter<{}>;
    plyrExitFullScreen: EventEmitter<{}>;
    plyrCaptionsEnabled: EventEmitter<{}>;
    plyrCaptionsDisabled: EventEmitter<{}>;
    plyrLanguageChange: EventEmitter<{}>;
    plyrControlsHidden: EventEmitter<{}>;
    plyrControlsShown: EventEmitter<{}>;
    plyrReady: EventEmitter<{}>;
    plyrLoadStart: EventEmitter<{}>;
    plyrLoadedData: EventEmitter<{}>;
    plyrLoadedMetadata: EventEmitter<{}>;
    plyrQualityChange: EventEmitter<{}>;
    plyrCanPlay: EventEmitter<{}>;
    plyrCanPlayThrough: EventEmitter<{}>;
    plyrStalled: EventEmitter<{}>;
    plyrWaiting: EventEmitter<{}>;
    plyrEmptied: EventEmitter<{}>;
    plyrCueChange: EventEmitter<{}>;
    plyrError: EventEmitter<{}>;
    plyrStateChange: EventEmitter<{}>;
    private subscriptions;
    private driver;
    private videoElement;
    constructor(elementRef: ElementRef<HTMLDivElement>, ngZone: NgZone, renderer: Renderer2);
    ngOnChanges(changes: {
        [p in keyof PlyrComponent]?: SimpleChange;
    }): void;
    ngOnDestroy(): void;
    ngAfterViewInit(): void;
    private initPlyr;
    private updatePlyrSource;
    private createLazyEvent;
    private destroyPlayer;
    private readonly hostElement;
    private ensureVideoElement;
    private on;
    private off;
}
